/// Flutter icons PingPayIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PingPayIcons
///      fonts:
///       - asset: fonts/PingPayIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PingPayIcons {
  PingPayIcons._();

  static const _kFontFam = 'PingPayIcons';

  static const IconData fingerprint_default = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_about = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_account = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_add = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_asset = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ic_coinin = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ic_coinout = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ic_coinpurse = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData ic_done = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData ic_eth = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData ic_minus = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData ic_notification = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData ic_recipt = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData ic_scan = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData ic_send = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData ic_eyeoff = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData ic_eyeon = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData ic_settings = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData ic_wallet = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData ic_xpa = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData icon = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData screenshot = const IconData(0xe815, fontFamily: _kFontFam);
}
